project:
  type: website
  render:
    - "*.qmd"
    - "!todo/*"
  output-dir: docs/

website:
  title: "Statistics Support FAQs"
  navbar:
    left:
      - href: index.html
        text: Home
    right:
      - text: "About"
        menu:
        - text: "thing1 template"
          href: template.html


format:
  html:
    toc: true
    toc_float: true
    theme:
      - united
      - assets/style-labs.scss
    include-in-header: "assets/toggling.html"
    number-sections: false


