project:
  type: website
  render:
    - "*.qmd"
    - "!todo/*"
    - "!archive/*"
  output-dir: docs/

website:
  title: "Statistics Support FAQs"
  navbar:
    left:
      - href: https://uoepsy.github.io
        text: Home
    right:
      - text: "Additional Docs"
        menu:
          - surveywrangle.qmd



format:
  html:
    toc: true
    toc_float: true
    theme:
      - united
      - assets/style-labs.scss
    include-in-header: "assets/toggling.html"
    number-sections: false


